FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y libpq-dev
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python","retrieve.py"]

